[package]
name = "arboard-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = { version = "3.2.0", features = ["image"] }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
